name: Android Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine/gradle:6.7.1-jdk11-alpine
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Gradle
        run: gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
